site_name: SweetBean
repo_url: 'https://github.com/AutoResearch/sweetbean'
site_url: 'https://autoresearch.github.io/sweetbean/'
edit_uri: 'blob/main/docs/'

extra:
  colab_base_url: 'https://colab.research.google.com/github/AutoResearch/sweetbean/blob/gh-pages/'

theme:
  name: material
  # logo: img/logo.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  custom_dir: mkdocs/overrides
  features:
    - navigation.indexes
    - content.code.copy
    - announce.dismiss

  extra:
    social:
      - icon: fontawesome/brands/github-alt
        link: https://github.com/AutoResearch

hooks:
  - mkdocs/hooks.py


watch:
  - src/sweetbean/
  - examples/

plugins:
  - search
  - gen-files:
      scripts:
        - mkdocs/gen_ref_pages.py
        - mkdocs/gen_example_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://scikit-learn.org/stable/objects.inv
  - mkdocs-jupyter: # required to convert Jupyter notebooks
      include_source: true
      execute: false




markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


nav:
  - Introduction: 'index.md'
  - Tutorials: 'tutorials.md'
  - Notebooks:
      - LLM Example: 'Notebooks/Basic LLM Experiment.ipynb'
  - Code Reference: reference/  #
  - Examples: examples/

## yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
#
#site_name: SweetBean
#
#theme:
#  name: material
#  features:
#    - navigation.tabs
#    - navigation.sections
#    - toc.integrate
#    - navigation.top
#    - search.suggest
#    - search.highlight
#    - content.tabs.link
#    - content.code.annotation
#    - content.code.copy
#  language: en
#  palette:
#    - scheme: default
#      toggle:
#        icon: material/toggle-switch-off-outline
#        name: Switch to dark mode
#      primary: default
#      accent: purple
#    - scheme: slate
#      toggle:
#        icon: material/toggle-switch
#        name: Switch to light mode
#      primary: default
#      accent: lime
#
#extra:
#  social:
#    - icon: fontawesome/brands/github-alt
#      link: https://github.com/AutoResearch
#
#
#
#watch:
#  - src/sweetbean/
#  - examples/
#
#plugins:
#  - search
#  - gen-files:
#      scripts:
#        - docs/gen_ref_pages.py
#        - docs/gen_example_pages.py
#  - literate-nav:
#        nav_file: SUMMARY.md
#  - section-index
#  - mkdocstrings:
#      handlers:
#        python:
#          import:
#            - https://scikit-learn.org/stable/objects.inv
#  - mkdocs-jupyter: # required to convert Jupyter notebooks
#      include_source: true
#      execute: false
#
#
#
#
#markdown_extensions:
#  - pymdownx.arithmatex:
#      generic: true
#
#extra_javascript:
#  - javascripts/mathjax.js
#  - https://polyfill.io/v3/polyfill.min.js?features=es6
#  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
#
#
#nav:
#- Introduction: 'index.md'
#- Tutorials: 'tutorials.md'
#- Notebooks:
#    - LLM Example: 'Notebooks/Basic LLM Experiment.ipynb'
#- Code Reference: reference/  #
#- Examples: examples/